name: Dive Action v2
description: Run Dive to analyze the container image efficiency
author: '@MaxymVlasov'
branding:
  icon: aperture
  color: green
inputs:
  image:
    description: Image to analyze
    required: true
  always-comment:
    description: Post dive analysis results as PR comment regardless of whether
      any inefficiencies were found. By default, comments are only posted when
      issues are detected. Requires `github-token`
    required: false
    default: 'false'
  config-file:
    description: Path to dive config file
    required: false
    default: ${{ github.workspace }}/.dive.yaml
  github-token:
    description: GitHub token to post PR comment with dive analysis
    required: false
  dive-image-registry:
    description: Docker registry to pull the Dive image from
    required: false
    default: ghcr.io/joschi/dive
  dive-image-version:
    description: >-
      Version of the Dive docker image to use. While `latest` is supported,
      using a specific version with SHA is recommended for security and reproducibility
    required: false
    default: 0.13.1@sha256:f016a4bd2837130545e391acee7876aa5f7258ccdb12640ab4afaffa1c597d17

runs:
  using: node20
  main: dist/index.js
