name: build
on:  # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:  # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - run: npm install
      - run: npm run all

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        params:
          - name: 'Params: image'
            image: ghcr.io/joschi/dive:latest
            github-token: ''
          - name: 'Params: image, github-token'
            image: ghcr.io/joschi/dive:latest
            github-token: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - name: ${{ matrix.params.name }}
        uses: ./
        with:
          image: ${{ matrix.params.image }}
          github-token: ${{ matrix.params.github-token }}
