name: build
on:  # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
    - main

permissions:
  contents: read

jobs:
  build:  # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
    - run: npm install
    - run: npm run all
  test:  # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
    - uses: ./
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        image: ghcr.io/joschi/dive:latest
